[2024-05-04T11:50:16.876+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-04T11:50:17.261+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: emaildag.testingfunc scheduled__2024-05-03T00:00:00+00:00 [queued]>
[2024-05-04T11:50:17.408+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: emaildag.testingfunc scheduled__2024-05-03T00:00:00+00:00 [queued]>
[2024-05-04T11:50:17.506+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2024-05-04T11:50:18.038+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): testingfunc> on 2024-05-03 00:00:00+00:00
[2024-05-04T11:50:18.167+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'emaildag', 'testingfunc', 'scheduled__2024-05-03T00:00:00+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/emaildag.py', '--cfg-path', '/tmp/tmpeq1hy863']
[2024-05-04T11:50:18.199+0000] {standard_task_runner.py:91} INFO - Job 47: Subtask testingfunc
[2024-05-04T11:50:18.211+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=572) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-04T11:50:18.215+0000] {standard_task_runner.py:63} INFO - Started process 590 to run task
[2024-05-04T11:50:28.267+0000] {cli_action_loggers.py:137} WARNING - Failed to log action (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-05-04T11:50:55.572+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 47 for task testingfunc ((psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8); 590)
[2024-05-04T11:51:35.348+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-04T11:51:35.644+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-04T11:51:35.685+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
